### PR TITLE
fixes #1 - added ASC command - replaced absolute path with global variable

### LINKED ISSUE #1: switchaudiosource path not correct
Hi @beet,
I've installed switchaudiosource with homebrew and it has been installed in the homebrew bin path "/opt/homebrew/bin"

To let your workflow works I had to replace all the "/usr/bin" path in the scripts with the homebrew's one.

### PR DESCRIPTION
**Pull request by Jeffr89**

### CODE REVIEW

**Comment by beet** [comment]
Nice one, thanks for taking the time to fork it and make a pull request!

On my machine, the binary is in a different source, so I had to modify the configuration script to:

```bash
query=$1

if [ "$query" ]; then
	SWITCHPATH="$1"
elif [ -f /usr/lib/switchaudiosource ]; then
    SWITCHPATH="/usr/lib/switchaudiosource"
elif [ -f /opt/homebrew/bin/switchaudiosource ]; then
	SWITCHPATH="/opt/homebrew/bin/switchaudiosource"
elif [ -f /usr/local/bin/switchaudiosource ]; then
	SWITCHPATH="/usr/local/bin/switchaudiosource"
else
	SWITCHPATH="nf"
fi

/usr/libexec/PlistBuddy -c "Set :variables:audioswitch_path \"$SWITCHPATH\"" info.plist
```

Then if I run the configure action it is able to find the binary, and the other actions work.

I wonder if it would be possible to insert the configuration script between the switcher script and another conditional to test whether `audioswitch_path` has been set? I think it takes a second or two changes written to the plist file by PlistBuddy to take effect though.

**Comment by Jeffr89** [comment]
I will try to do it during this week.
Just to be sure, in ur machine, does "which switchaudiosource" return the correct path? 
In this case, I could just use this function to get the right path, leaving the possibilities to set it throught `asc "arg path"`

**Comment by beet** [comment]
Ah, yes it does, that's how I verified the path actually 😀

**Comment by jgimeno** [comment]
Can we merge this?

**Comment by beet** [comment]
> Can we merge this?

I pulled down the fork and make some tweaks to accomodate my local path for the `switchaudiosource` binary, and automatically run the configuration step instead of having to invoke it manually, but don't seem to be able to push them back up.

Haven't worked with forks like this before, only on internal repos owned by the companies I work for :) 

I have a couple of commits locally, what's the best way to get them into this PR so we can merge it into `main` and do a release?

**Comment by Jeffr89** [comment]
Honestly I don't know :) 
Maybe you can push your tweaks to the fork and than do a new PR.

**Comment by jgimeno** [comment]
I created a simbolic link to the one that comes from default in the plugin and it works.

**Pull request merged**
